version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'find'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '32000:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  app:
    build: ./find_neighbors
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  my-db:
